version: '3'
services:
  web:
    image: docker-bimserver:109
    ports:
     - "8090:8080"
    volumes:
     - database:/usr/local/tomcat/webapps/bimserver/WEB-INF/database
     - plugins:/usr/local/tomcat/webapps/bimserver/WEB-INF/plugins
volumes:
  database:
  plugins:
